### ISSUE TITLE
0001.forked PHP Warning

### ISSUE THREAD

**Issue by rickvschmidt** [austinginder/recipe-card#1]
Thanks for working on this forked version. 

I installed your 0001.forked version yesterday, and my client was able to save again. However we're getting this weird PHP warning at the top of a post that contains a recipe card. It only apply to new cards created since the fork:

`Warning: Invalid argument supplied for foreach() in /home4/cookbook13/public_html/wp-content/plugins/recipe-card/yumprint-recipe.php on line 610`

It appears to deal with the nutrition information. Have any ideas?

**Comment by rickvschmidt** [comment]
As a temporary solution I came up with the following fix, which seams to work. Though I must admit there's probably a deeper issue at play. The function that this is in is pretty messy and I don't think it makes sense to refactor their code at this juncture. 

`if ( is_array($nutrition) || ($nutrition instanceof Traversable) ) {
      foreach ($nutrition as $key => &$value) {
         $value /= $div;
      }
}`

**Comment by austinginder** [comment]
Curious if it's a PHP version issue. What version of PHP are you using? From a data standpoint, there is now less info being saved to the database. If I had to guess I would say it's not happy about some of the fields which are now empty (yumprint_id, yumprint_key).

**Comment by rickvschmidt** [comment]
Hate to say it but running 5.3 on this clients' site since that what their hosting provider uses by default. Could probably bump it up if need be, but the code should probably be fixed to work on this version since a lot of people are still there...

**Comment by austinginder** [comment]
Got it. Yes so it sounds like it's a PHP version thing. I tested out your code mod and it seems to work the same. I just included your code in the latest commit. Can you try it now?

**Comment by gottalovelattes** [comment]
The PHP fix worked for me...thanks guys.

**Comment by austinginder** [comment]
Great. Thanks to @rickvschmidt for submitting a workaround.

**Comment by anurag3003** [comment]
Hi Austin, 

I tried using your forked version of yumprint. i kept the old recipe card plug as it is and then created another folder in cpanel plugin dir and uploaded your forked version. Since the function names were conflicting b/w 2 plugins  so i appended the the fuctions in forked version with _fork and after many attempts was able to successfully active the plugin ..but when i tried using this plug in , it is still throwing the same messages that the receipe cant be saved and need to contact yumprint support. can you please let me know if this is wrong way of doing . i dont want to disable the old plug in since i would loose all the receipe content .. thanks...

**Comment by austinginder** [comment]
@anurag3003 This fork is meant to be used as a replacement. Deactivating the official plugin won't remove your recipes. I would first deactivate and remove the official plugin then install this one. That said this isn't a fully featured plugin. It's just a few patches to workaround Yumprint's server issues. There is no active development here.
